apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  #因为LB需要额外的模块，因此在我的实验室里用Nodeport
  #type: LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011 #Node端口
  selector:
    name: result-app-pod
    app: demo-voting-app
